# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bifrost < Formula
  desc "Cross-platform collaboration tool for file transfer, sharing, and synchronization"
  homepage "https://www.databifrost.com"
  version "1.1.4-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leoon-ding/homebrew-tap/releases/download/bifrost/1.1.4-test/bifrost_v1.1.4-test_darwin_x86_64.tar.gz"
      sha256 "d6785d20a2cf1e60426ad18c001b4da2d4363ac5bc8486485bfa1c8b63266e66"

      define_method(:install) do
        bin.install "bifrost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leoon-ding/homebrew-tap/releases/download/bifrost/1.1.4-test/bifrost_v1.1.4-test_darwin_arm64.tar.gz"
      sha256 "01f07815d6a6954d101bde300ea8b2663fcd7d574d03733dab10e9edb36ef440"

      define_method(:install) do
        bin.install "bifrost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leoon-ding/homebrew-tap/releases/download/bifrost/1.1.4-test/bifrost_v1.1.4-test_linux_x86_64.tar.gz"
      sha256 "a56654bf42f55e921aab4ea3a963a7a519726f7a7207f055ce6d1096d39e32a1"
      define_method(:install) do
        bin.install "bifrost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leoon-ding/homebrew-tap/releases/download/bifrost/1.1.4-test/bifrost_v1.1.4-test_linux_arm64.tar.gz"
      sha256 "ccbc925bc603f12b621937e63462af1f721ddb4b0d0ed8c0e0ec9558e4b7d0ca"
      define_method(:install) do
        bin.install "bifrost"
      end
    end
  end

  test do
    system "#{bin}/bifrost", "--version"
  end
end
